using OpenGarrison.Core;

namespace OpenGarrison.MLBot.Contracts;

public readonly record struct MLBotObservation(
    byte Slot,
    string LevelName,
    GameModeKind Mode,
    PlayerTeam Team,
    PlayerClass ClassId,
    MLBotTaskPhase TaskPhase,
    float BotX,
    float BotY,
    float VelocityX,
    float VelocityY,
    bool IsGrounded,
    float FacingDirectionX,
    int Health,
    int MaxHealth,
    bool IsCarryingIntel,
    MLBotObjectiveSnapshot Objective,
    MLBotWaypointSnapshot Waypoint,
    MLBotTraversalSnapshot Traversal,
    MLBotControlPointObjectiveSnapshot ControlPointObjective,
    MLBotProbeSnapshot Probes,
    MLBotActorSummary NearestVisibleEnemy,
    MLBotActorSummary NearestVisibleTeammate,
    float StuckTicks,
    float ObjectiveDistance,
    float ObjectiveDistanceDelta,
    int ControlPointOwner,
    int ControlPointCappingTeam,
    float ControlPointCaptureProgress,
    bool ControlPointLocked,
    bool IsRespawning,
    int RemainingAirJumps,
    int MaxAirJumps,
    float RunPower,
    float MaxRunSpeed,
    float GroundAcceleration,
    float GroundDeceleration,
    float Gravity,
    float JumpSpeed,
    float Width,
    float Height,
    float PreviousVelocityX,
    float PreviousVelocityY,
    float PreviousPositionDeltaX,
    float PreviousPositionDeltaY,
    float PreviousObjectiveDistanceDelta,
    float PreviousFacingDirectionX,
    bool PreviousIsGrounded,
    float AirborneTicks,
    float JumpTicks,
    int PreviousMoveInput,
    bool PreviousJumpPressed,
    bool PreviousJumpHeld,
    bool PreviousDropInput,
    bool PreviousActionFirePrimary,
    bool PreviousActionFireSecondary,
    bool PreviousActionDropIntel,
    float FramesSinceJumpPressed,
    float FramesSinceJumpReleased,
    MLBotTerrainAffordanceSnapshot TerrainAffordance);

public readonly record struct MLBotObjectiveSnapshot(
    bool HasObjective,
    float WorldX,
    float WorldY,
    float RelativeX,
    float RelativeY,
    float HomeX,
    float HomeY,
    float HomeRelativeX,
    float HomeRelativeY);

public readonly record struct MLBotWaypointSnapshot(
    bool HasWaypoint,
    float WorldX,
    float WorldY,
    float RelativeX,
    float RelativeY,
    float Distance,
    bool IsFinalWaypoint);

public enum MLBotTraversalLinkKind
{
    UnknownCandidate = 0,
    Walk = 1,
    JumpUp = 2,
    JumpAcross = 3,
    DropDown = 4,
    Climb = 5,
    FallRecover = 6,
    Gate = 7,
}

public readonly record struct MLBotTraversalSnapshot(
    bool HasTraversal,
    MLBotTraversalLinkKind LinkKind,
    float ExpectedMoveDirection,
    float CurrentNodeRelativeX,
    float CurrentNodeRelativeY,
    float TargetNodeRelativeX,
    float TargetNodeRelativeY,
    float SegmentDeltaX,
    float SegmentDeltaY,
    float SegmentDistance,
    float SegmentProgress,
    float AllowedOvershootDistance,
    float MaxSegmentTicks,
    float SegmentDifficulty,
    float SegmentTicks,
    float AttemptCount);

public readonly record struct MLBotControlPointObjectiveSnapshot(
    bool HasObjective,
    int Index,
    int Owner,
    int CappingTeam,
    float CaptureProgress,
    float CaptureProgressDelta,
    bool IsLocked,
    int FriendlyCappers,
    int EnemyCappers,
    int TotalCappers,
    bool IsContested,
    bool IsPlayerInCaptureZone,
    float TimeOnPointTicks,
    float TimeSinceLeftPointTicks,
    int FriendlyKothTimerTicksRemaining,
    int EnemyKothTimerTicksRemaining,
    int KothUnlockTicksRemaining,
    bool IsKothMode,
    bool IsDoubleKothMode);

public readonly record struct MLBotProbeSnapshot(
    float ForwardFootObstacleDistance,
    float ForwardHeadObstacleDistance,
    float GroundAheadDistance,
    float DropAheadDepth,
    float CeilingDistance,
    float LedgeHeightAhead,
    bool BlockingGateAhead,
    float LeftFootObstacleDistance,
    float LeftHeadObstacleDistance,
    float RightFootObstacleDistance,
    float RightHeadObstacleDistance,
    float LeftGroundDistance,
    float RightGroundDistance,
    float LeftDropDepth,
    float RightDropDepth,
    bool TouchingLeftWall,
    bool TouchingRightWall,
    bool TouchingCeiling);

public readonly record struct MLBotTerrainAffordanceSnapshot(
    bool HasLeftLanding,
    float LeftLandingRelativeX,
    float LeftLandingRelativeY,
    float LeftLandingSurfaceDeltaY,
    float LeftLandingObjectiveDistanceDelta,
    bool LeftLandingIsHigher,
    bool LeftLandingRequiresJump,
    bool HasRightLanding,
    float RightLandingRelativeX,
    float RightLandingRelativeY,
    float RightLandingSurfaceDeltaY,
    float RightLandingObjectiveDistanceDelta,
    bool RightLandingIsHigher,
    bool RightLandingRequiresJump,
    bool HasBestUpwardLanding,
    float BestUpwardLandingRelativeX,
    float BestUpwardLandingRelativeY,
    float BestUpwardLandingSurfaceDeltaY,
    float BestUpwardLandingObjectiveDistanceDelta,
    float BestUpwardLandingDirection,
    bool BestUpwardLandingMovesAwayFromObjective,
    float BestUpwardLandingHorizontalGap,
    float BestUpwardLandingHeadroom,
    float CurrentSurfaceClearanceLeft,
    float CurrentSurfaceClearanceRight);

public readonly record struct MLBotActorSummary(
    bool Exists,
    float RelativeX,
    float RelativeY,
    float Distance,
    bool HasLineOfSight);
