using OpenGarrison.Core;

namespace OpenGarrison.MLBot.Contracts;

public sealed record MLBotEpisodeConfig(
    string LevelName,
    int MapAreaIndex,
    PlayerTeam Team,
    PlayerClass ClassId,
    MLBotTaskPhase TaskPhase,
    int MaxTicks,
    int StartNodeId = -1,
    float? StartX = null,
    float? StartY = null,
    float? StartVelocityX = null,
    float? StartVelocityY = null,
    bool? CarryingIntel = null,
    bool? StartIsGrounded = null,
    int? StartRemainingAirJumps = null,
    float? StartFacingDirectionX = null,
    int? StartPreviousMoveInput = null,
    bool? StartPreviousJumpHeld = null,
    bool? StartPreviousDropInput = null,
    bool? StartPreviousFirePrimary = null,
    bool? StartPreviousFireSecondary = null,
    float? StartPreviousPositionDeltaX = null,
    float? StartPreviousPositionDeltaY = null,
    float? StartPreviousVelocityX = null,
    float? StartPreviousVelocityY = null,
    float? StartPreviousFacingDirectionX = null,
    bool? StartPreviousIsGrounded = null,
    float? StartObjectiveDistance = null,
    float? StartObjectiveDistanceDelta = null,
    float? StartPreviousObjectiveDistanceDelta = null,
    float? StartAirborneTicks = null,
    float? StartJumpTicks = null,
    float? StartFramesSinceJumpPressed = null,
    float? StartFramesSinceJumpReleased = null)
{
    public static MLBotEpisodeConfig CreateDefault(
        string levelName,
        MLBotTaskPhase taskPhase,
        PlayerTeam team = PlayerTeam.Red,
        PlayerClass classId = PlayerClass.Scout,
        int maxTicks = 1800,
        int startNodeId = -1,
        float? startX = null,
        float? startY = null,
        float? startVelocityX = null,
        float? startVelocityY = null,
        bool? carryingIntel = null,
        bool? startIsGrounded = null,
        int? startRemainingAirJumps = null,
        float? startFacingDirectionX = null,
        int? startPreviousMoveInput = null,
        bool? startPreviousJumpHeld = null,
        bool? startPreviousDropInput = null,
        bool? startPreviousFirePrimary = null,
        bool? startPreviousFireSecondary = null,
        float? startPreviousPositionDeltaX = null,
        float? startPreviousPositionDeltaY = null,
        float? startPreviousVelocityX = null,
        float? startPreviousVelocityY = null,
        float? startPreviousFacingDirectionX = null,
        bool? startPreviousIsGrounded = null,
        float? startObjectiveDistance = null,
        float? startObjectiveDistanceDelta = null,
        float? startPreviousObjectiveDistanceDelta = null,
        float? startAirborneTicks = null,
        float? startJumpTicks = null,
        float? startFramesSinceJumpPressed = null,
        float? startFramesSinceJumpReleased = null)
        => new(
            levelName,
            1,
            team,
            classId,
            taskPhase,
            maxTicks,
            startNodeId,
            startX,
            startY,
            startVelocityX,
            startVelocityY,
            carryingIntel,
            startIsGrounded,
            startRemainingAirJumps,
            startFacingDirectionX,
            startPreviousMoveInput,
            startPreviousJumpHeld,
            startPreviousDropInput,
            startPreviousFirePrimary,
            startPreviousFireSecondary,
            startPreviousPositionDeltaX,
            startPreviousPositionDeltaY,
            startPreviousVelocityX,
            startPreviousVelocityY,
            startPreviousFacingDirectionX,
            startPreviousIsGrounded,
            startObjectiveDistance,
            startObjectiveDistanceDelta,
            startPreviousObjectiveDistanceDelta,
            startAirborneTicks,
            startJumpTicks,
            startFramesSinceJumpPressed,
            startFramesSinceJumpReleased);
}
