namespace OpenGarrison.Core;

public enum RoomObjectType
{
    HealingCabinet = 1,
    TeamGate = 2,
    ArenaControlPoint = 3,
    CaptureZone = 4,
    ControlPoint = 5,
    ControlPointSetupGate = 6,
    Generator = 7,
    IntelGate = 8,
    PlayerWall = 9,
    BulletWall = 10,
    SpawnRoom = 11,
    FragBox = 12,
    KillBox = 13,
    DropdownPlatform = 14,
    MoveBoxUp = 15,
    MoveBoxDown = 16,
    MoveBoxLeft = 17,
    MoveBoxRight = 18,
    Barrier = 19,
    DirectionalWall = 20,
    TeleportZone = 21,
    TeleportExit = 22,
    PlayerTriggerZone = 23,
    CustomMapSprite = 24,
    AreaExtension = 25,
    DamageableZone = 26,
}
