namespace OpenGarrison.Core;

public sealed record ExperimentalGameplaySettings(
    bool EnableSecondaryAbilities = true,
    bool EnableSoldierFastCapture = false,
    bool EnableDemoknightFastCapture = false,
    bool EnableDemoknightKit = false,
    bool EnableCapturedPointHealingAura = false,
    bool EnableSoldierShotgunSecondaryWeapon = false,
    bool EnableSoldierAmmoRegeneratesWhileSwappedOut = false,
    bool EnableSoldierStingerRockets = false,
    bool EnableSoldierInfiniteAmmoDuringRage = false,
    bool EnableSoldierRageExtensionOnKill = false,
    bool EnableSoldierRageCaptureLockout = false,
    bool EnableSoldierRageCaptureDuringRage = false,
    bool EnableSoldierNapalmRockets = false,
    bool EnableSoldierFinalClipRocketBurst = false,
    bool EnableSoldierCivilDefenseTurret = false,
    bool EnableSoldierLuckyBastard = false,
    bool EnableSoldierThundergunner = false,
    bool EnableSoldierBattleborn = false,
    bool EnableSoldierFogOfWar = false,
    bool EnableSoldierDangerClose = false,
    bool EnableHealOnDamage = false,
    bool EnableHealOnKill = false,
    bool EnableSelfDamageHealing = false,
    bool EnableRage = false,
    bool EnableRateOfFireMultiplierOnDamage = false,
    bool EnableSoldierInstantReload = false,
    bool EnableSpeedOnDamage = false,
    bool EnableSpeedOnKill = false,
    bool EnablePassiveHealthRegeneration = false,
    bool EnableInvincibilityOnKill = false,
    bool EnableGhostPhaseOnKill = false,
    bool EnableProjectileSpeedMultiplier = false,
    bool EnableAirshotDamageMultiplier = false,
    bool EnableComboTracking = false,
    bool EnableKillStreakTracking = false,
    bool EnableEnemyHealthPackDrops = false,
    bool EnableEnemyDroppedWeapons = false,
    bool EnablePracticeBotsPrioritizeKills = false,
    float EnemyHealthPackDropChance = 0.1f,
    float HealOnDamageFraction = 0.35f,
    int HealOnKillAmount = 25,
    float KillInvincibilityDurationSeconds = 0.5f,
    float PassiveHealthRegenerationPerSecond = 3f,
    float ProjectileSpeedMultiplierValue = 1.2f,
    float AirshotDamageMultiplierValue = 1.25f,
    float ReloadSpeedMultiplierValue = 1f,
    float PassiveMovementSpeedMultiplier = 1f,
    float PassiveJumpHeightMultiplier = 1f,
    int PassiveBonusAirJumps = 0,
    float PassiveEvasionChance = 0f,
    float PassiveThornsFraction = 0f,
    float PassiveDamageResistance = 0f,
    float PassiveDamageMultiplier = 1f,
    float AcquiredWeaponDamageMultiplier = 1f,
    float AcquiredWeaponHealingMultiplier = 1f,
    int BonusProjectilesPerShot = 0,
    int SoldierShotgunPelletMultiplier = 1,
    float DemoknightSwordRangeMultiplier = 1f,
    int DemoknightSwordBaseDamage = 42,
    float DemoknightSwordDamageMultiplier = 1f,
    float DemoknightSwordCooldownMultiplier = 1f,
    float DemoknightChargeRechargeMultiplier = 1f,
    float DemoknightChargeDamageTakenMultiplier = 1f,
    bool EnableFullHealOnKill = false,
    bool EnableDemoknightPostRageRegeneration = false,
    bool EnableDemoknightFullControlDuringCharge = false,
    bool EnableDemoknightGhostDash = false)
{
    public const float CapturedPointHealingPerSecond = 8f;
    public const float DefaultEnemyHealthPackDropChance = 0.1f;
    public const float DefaultHealOnDamageFraction = 0.35f;
    public const int DefaultHealOnKillAmount = 25;
    public const float DefaultPassiveHealthRegenerationPerSecond = 3f;
    public const float RageMaxCharge = 500f;
    public const float RageDamageDealtChargeMultiplier = 1f;
    public const float RageDamageReceivedChargeMultiplier = 1f;
    public const float RageDurationSeconds = 7f;
    public const float SpeedBoostMultiplier = 1.2f;
    public const float RateOfFireCooldownMultiplier = 0.8f;
    public const float OnDamageBuffDurationSeconds = 2.5f;
    public const float OnKillBuffDurationSeconds = 3f;
    public const float DefaultKillInvincibilityDurationSeconds = 0.5f;
    public const float DefaultPassiveMovementSpeedMultiplier = 1f;
    public const float DefaultPassiveJumpHeightMultiplier = 1f;
    public const float DefaultDemoknightSwordRangeMultiplier = 1f;
    public const int DefaultDemoknightSwordBaseDamage = 42;
    public const float DefaultDemoknightSwordDamageMultiplier = 1f;
    public const float DefaultDemoknightSwordCooldownMultiplier = 1f;
    public const float DefaultDemoknightChargeRechargeMultiplier = 1f;
    public const float DefaultDemoknightChargeDamageTakenMultiplier = 1f;
    public const float DefaultProjectileSpeedMultiplier = 1.2f;
    public const float DefaultAirshotDamageMultiplier = 1.25f;
    public const float DefaultReloadSpeedMultiplier = 1f;
    public const float DefaultSoldierStingerRocketSpeedMultiplier = 0.3f;
    public const float DefaultSoldierStingerRocketTurnRateDegrees = 7.5f;
    public const float DefaultSoldierStingerDamageMultiplier = 2f;
    public const float DefaultSoldierStingerBlastRadiusMultiplier = 1.6f;
    public const float DefaultSoldierStingerBurstSpeedMultiplier = 2f;
    public const float DefaultSoldierStingerManualDetonationSelfKnockbackMultiplier = 3f;
    public const float DefaultSoldierRageExtensionSecondsPerKill = 2f;
    public const float DefaultDangerCloseBlastRadius = 72f;
    public const float DefaultDangerCloseExplosionDamage = 34f;
    public const float DefaultDangerCloseKnockbackPerTick = 7f;
    public const float DefaultDemoknightPostRageRegenerationPerSecond = 35f;
    public const float DefaultDemoknightPostRageRegenerationDurationSeconds = 10f;
    public const float DefaultSoldierCriticalInvincibilityDurationSeconds = 3f;
    public const float DefaultSoldierNapalmAfterburnIntensity = 1.2f;
    public const float DefaultSoldierNapalmAfterburnDurationSourceTicks = 90f;
    public const float DefaultSoldierNapalmGravityMultiplier = 1.45f;
    public const float DefaultSoldierFinalRocketDamageMultiplier = 1.25f;
    public const float DefaultSoldierLuckyBastardInvincibilityDurationSeconds = 5f;
    public const int DefaultSoldierLuckyBastardMinimumKills = 3;
    public const float DefaultSoldierFogOfWarInitialEvasionChance = 0.02f;
    public const float DefaultSoldierFogOfWarWindowSeconds = 3f;
    public const int DefaultSoldierCivilDefenseTurretDeployCooldownTicks = 30;
    public const int DefaultSoldierThundergunnerCooldownTicks = 24;
    public const float DefaultSoldierThundergunnerEmptyClipForceMultiplier = 2f;
    public const float DefaultGhostDashDurationSeconds = 0.5f;
    public const float DefaultGhostDashCooldownSeconds = 1f;
    public const float DefaultGhostDashNextAttackDamageMultiplier = 1.4f;
    public const float ComboTimeoutSeconds = 6f;
    public const float MultiKillWindowSeconds = 3f;
    public const float EnemyHealthPackLargeChance = 0.5f;
    public const float EnemyDroppedWeaponChance = 0.5f;
}
