namespace OpenGarrison.GameplayModding;

public sealed record GameplayItemPresentationDefinition(
    string? WorldSpriteName = null,
    string? RecoilSpriteName = null,
    string? ReloadSpriteName = null,
    string? RecoilCarrierSpriteName = null,
    string? RecoilOverlaySpriteName = null,
    float RecoilOverlayOffsetX = 0f,
    float RecoilOverlayOffsetY = 0f,
    float RecoilOverlayRotationDegrees = 0f,
    string? ReloadCarrierSpriteName = null,
    string? ReloadOverlaySpriteName = null,
    float ReloadOverlayOffsetX = 0f,
    float ReloadOverlayOffsetY = 0f,
    float ReloadOverlayRotationDegrees = 0f,
    string? HudSpriteName = null,
    float WeaponOffsetX = 0f,
    float WeaponOffsetY = 0f,
    int RecoilDurationSourceTicks = 0,
    int ReloadDurationSourceTicks = 0,
    int ScopedRecoilDurationSourceTicks = 0,
    bool LoopRecoilWhileActive = false,
    int BlueTeamHudFrameOffset = 1,
    bool UseAmmoCountForHudFrame = false,
    int BlueTeamAmmoHudFrameOffset = 0);
