using System.Text;
using System.Text.RegularExpressions;

var options = GeneratorOptions.Parse(args);
var repositoryRoot = options.RepositoryRoot ?? FindRepositoryRoot(AppContext.BaseDirectory);
var clientSourcePath = Path.Combine(repositoryRoot, "Client", "Plugins", "LuaClientPlugin.cs");
var serverSourcePath = Path.Combine(repositoryRoot, "Server", "Plugins", "LuaServerPlugin.cs");
var outputPath = options.OutputPath ?? Path.Combine(
    repositoryRoot,
    "Plugins",
    "OpenGarrison.PluginHost.Abstractions",
    "LuaHostApiSurface.g.cs");

if (!File.Exists(clientSourcePath))
{
    Console.Error.WriteLine($"Client Lua host source was not found: {clientSourcePath}");
    return 2;
}

if (!File.Exists(serverSourcePath))
{
    Console.Error.WriteLine($"Server Lua host source was not found: {serverSourcePath}");
    return 2;
}

var clientFunctions = LuaHostApiBindingScanner.Scan(clientSourcePath);
var serverFunctions = LuaHostApiBindingScanner.Scan(serverSourcePath);
var generatedSource = LuaHostApiSurfaceSourceBuilder.Build(clientFunctions, serverFunctions);

if (options.CheckOnly)
{
    if (!File.Exists(outputPath))
    {
        Console.Error.WriteLine($"Generated Lua host API surface file was not found: {outputPath}");
        return 1;
    }

    var existingSource = File.ReadAllText(outputPath);
    if (!string.Equals(existingSource, generatedSource, StringComparison.Ordinal))
    {
        Console.Error.WriteLine("Generated Lua host API surface is out of date. Run:");
        Console.Error.WriteLine($"  dotnet run --project Tools/OpenGarrison.PluginHost.ApiGenerator/OpenGarrison.PluginHost.ApiGenerator.csproj -- --repo-root \"{repositoryRoot}\"");
        return 1;
    }

    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");
File.WriteAllText(outputPath, generatedSource, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Wrote {outputPath}");
return 0;

static string FindRepositoryRoot(string startDirectory)
{
    var directory = new DirectoryInfo(startDirectory);
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "OpenGarrison.sln"))
            && Directory.Exists(Path.Combine(directory.FullName, "Client"))
            && Directory.Exists(Path.Combine(directory.FullName, "Server")))
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    throw new InvalidOperationException("Could not find repository root.");
}

internal sealed record GeneratorOptions(string? RepositoryRoot, string? OutputPath, bool CheckOnly)
{
    public static GeneratorOptions Parse(string[] args)
    {
        string? repositoryRoot = null;
        string? outputPath = null;
        var checkOnly = false;

        for (var index = 0; index < args.Length; index += 1)
        {
            switch (args[index])
            {
                case "--repo-root":
                    repositoryRoot = RequireValue(args, ref index, "--repo-root");
                    break;
                case "--output":
                    outputPath = RequireValue(args, ref index, "--output");
                    break;
                case "--check":
                    checkOnly = true;
                    break;
                default:
                    throw new ArgumentException($"Unknown argument: {args[index]}");
            }
        }

        return new GeneratorOptions(
            repositoryRoot is null ? null : Path.GetFullPath(repositoryRoot),
            outputPath is null ? null : Path.GetFullPath(outputPath),
            checkOnly);
    }

    private static string RequireValue(string[] args, ref int index, string option)
    {
        if (index + 1 >= args.Length)
        {
            throw new ArgumentException($"{option} requires a value.");
        }

        index += 1;
        return args[index];
    }
}

internal static partial class LuaHostApiBindingScanner
{
    private static readonly Regex HostBindingRegex = CreateHostBindingRegex();

    public static IReadOnlyList<string> Scan(string sourcePath)
    {
        var source = File.ReadAllText(sourcePath);
        return HostBindingRegex.Matches(source)
            .Select(match => match.Groups["name"].Value)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();
    }

    [GeneratedRegex("""host\["(?<name>[A-Za-z0-9_]+)"\]\s*=""", RegexOptions.CultureInvariant)]
    private static partial Regex CreateHostBindingRegex();
}

internal static class LuaHostApiSurfaceSourceBuilder
{
    public static string Build(IReadOnlyList<string> clientFunctions, IReadOnlyList<string> serverFunctions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("namespace OpenGarrison.PluginHost;");
        builder.AppendLine();
        builder.AppendLine("public static partial class OpenGarrisonLuaHostApiSurface");
        builder.AppendLine("{");
        builder.AppendLine("""    public const string ApiVersion = "1.0";""");
        builder.AppendLine();
        AppendFunctionList(builder, "ClientFunctions", clientFunctions);
        builder.AppendLine();
        AppendFunctionList(builder, "ServerFunctions", serverFunctions);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendFunctionList(StringBuilder builder, string propertyName, IReadOnlyList<string> functions)
    {
        builder.Append("    public static IReadOnlyList<string> ");
        builder.Append(propertyName);
        builder.AppendLine(" { get; } = CreateFunctionList(");
        for (var index = 0; index < functions.Count; index += 1)
        {
            var suffix = index + 1 == functions.Count ? ");" : ",";
            builder.Append("        \"");
            builder.Append(functions[index]);
            builder.Append('"');
            builder.AppendLine(suffix);
        }
    }
}
