using System.Security.Cryptography;
using System.Text.Json;

namespace OpenGarrison.Core;

/// <summary>Publishes immutable assets before atomically replacing their manifest.</summary>
internal static class MapPackageTransaction
{
    internal static void Write(string manifestPath, Action<string> build)
    {
        manifestPath = Path.GetFullPath(manifestPath);
        var directory = Path.GetDirectoryName(manifestPath)!;
        Directory.CreateDirectory(directory);
        var stage = Path.Combine(directory, ".builder-stage-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(stage);
        var added = new List<string>();
        var committed = false;
        try
        {
            var stagedManifest = Path.Combine(stage, Path.GetFileName(manifestPath));
            build(stagedManifest);
            if (CustomMapPackageImporter.ImportDocument(stagedManifest) is null)
                throw new InvalidDataException("The saved package could not be verified.");
            var manifest = JsonSerializer.Deserialize<CustomMapPackageManifest>(File.ReadAllText(stagedManifest), CustomMapPackageManifest.JsonOptions)!;
            var paths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var source in Directory.EnumerateFiles(stage).Where(p => p != stagedManifest))
            {
                var name = Path.GetFileName(source);
                var bytes = File.ReadAllBytes(source);
                var target = Path.Combine(directory, name);
                if (File.Exists(target) && !File.ReadAllBytes(target).AsSpan().SequenceEqual(bytes))
                {
                    name = Path.GetFileNameWithoutExtension(name) + "-" + Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant() + Path.GetExtension(name);
                    target = Path.Combine(directory, name);
                }
                if (File.Exists(target))
                {
                    if (!File.ReadAllBytes(target).AsSpan().SequenceEqual(bytes))
                        throw new IOException("An existing package asset conflicts with the saved data.");
                }
                else
                {
                    File.Move(source, target);
                    added.Add(target);
                }
                paths[Path.GetFileName(source)] = name;
            }
            manifest.BackgroundImage = paths[manifest.BackgroundImage];
            manifest.WalkmaskImage = paths[manifest.WalkmaskImage];
            foreach (var resource in manifest.Resources) resource.Path = paths[resource.Path];
            MapFileTransaction.Write(manifestPath, temporary => File.WriteAllText(temporary, JsonSerializer.Serialize(manifest, CustomMapPackageManifest.JsonOptions)));
            committed = true;
        }
        finally
        {
            if (!committed)
                foreach (var path in added) { try { File.Delete(path); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { } }
            // This directory is freshly generated by this operation; never a user-selected tree.
            try
            {
                foreach (var file in Directory.EnumerateFiles(stage)) File.Delete(file);
                Directory.Delete(stage);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { /* A cleanup failure must not misreport a committed save as failed. */ }
        }
    }
}
