namespace OpenGarrison.Core;

// Generated from SourceAssets/Sprites/Gibs/Gibs Sheet.aseprite by import_gibs.py.
// Coordinates are world pixels at the normal 2x player/gib art scale.
internal static class AuthoredPlayerGibPlacementCatalog
{
    private static readonly Dictionary<(string ClassId, string PartName), (float X, float Y)> Offsets = new()
    {
        [("civilian", "ChestA")] = (-4f, 2f),
        [("civilian", "ChestB")] = (4f, 0f),
        [("civilian", "Gun")] = (10f, 4f),
        [("civilian", "Head")] = (2f, -14f),
        [("civilian", "LegBottomL")] = (-4f, 20f),
        [("civilian", "LegBottomR")] = (6f, 20f),
        [("civilian", "LegTopL")] = (-6f, 12f),
        [("civilian", "LegTopR")] = (4f, 12f),
        [("scout", "Chest")] = (-2f, -2f),
        [("scout", "Gun")] = (0f, 0f),
        [("scout", "Hat")] = (2f, -14f),
        [("scout", "Head")] = (2f, -12f),
        [("scout", "LegBottomL")] = (-4f, 18f),
        [("scout", "LegBottomR")] = (6f, 18f),
        [("scout", "LegTopL")] = (-4f, 8f),
        [("scout", "LegTopR")] = (2f, 8f),
        [("soldier", "ChestA")] = (0f, 0f),
        [("soldier", "ChestB")] = (2f, 2f),
        [("soldier", "Gun")] = (2f, -4f),
        [("soldier", "Hat")] = (4f, -14f),
        [("soldier", "Head")] = (4f, -12f),
        [("soldier", "LegBottomL")] = (-8f, 18f),
        [("soldier", "LegBottomR")] = (12f, 18f),
        [("soldier", "LegTopL")] = (-2f, 10f),
        [("soldier", "LegTopR")] = (8f, 8f),
        [("pyro", "ChestA")] = (-8f, -10f),
        [("pyro", "ChestB")] = (-2f, -10f),
        [("pyro", "Gun")] = (2f, 0f),
        [("pyro", "Head")] = (2f, -18f),
        [("pyro", "LegBottomL")] = (-8f, 16f),
        [("pyro", "LegBottomR")] = (4f, 16f),
        [("pyro", "LegTopL")] = (-4f, 4f),
        [("pyro", "LegTopR")] = (2f, 4f),
        [("demoman", "ChestA")] = (-4f, -4f),
        [("demoman", "ChestB")] = (4f, -4f),
        [("demoman", "Gun")] = (2f, 0f),
        [("demoman", "Hat")] = (0f, -24f),
        [("demoman", "Head")] = (0f, -18f),
        [("demoman", "LegBottomL")] = (-10f, 18f),
        [("demoman", "LegBottomR")] = (4f, 18f),
        [("demoman", "LegTopL")] = (-8f, 10f),
        [("demoman", "LegTopR")] = (4f, 10f),
        [("heavy", "ChestA")] = (-8f, -4f),
        [("heavy", "ChestB")] = (4f, -4f),
        [("heavy", "Gun")] = (8f, 4f),
        [("heavy", "Head")] = (-4f, -20f),
        [("heavy", "LegBottomL")] = (-8f, 18f),
        [("heavy", "LegBottomR")] = (6f, 18f),
        [("heavy", "LegTopL")] = (-8f, 10f),
        [("heavy", "LegTopR")] = (2f, 8f),
        [("engineer", "ChestA")] = (-2f, -2f),
        [("engineer", "ChestB")] = (2f, -2f),
        [("engineer", "Gun")] = (8f, 0f),
        [("engineer", "Hat")] = (2f, -20f),
        [("engineer", "Head")] = (2f, -14f),
        [("engineer", "LegBottomL")] = (-6f, 18f),
        [("engineer", "LegBottomR")] = (6f, 18f),
        [("engineer", "LegTopL")] = (-4f, 10f),
        [("engineer", "LegTopR")] = (4f, 10f),
        [("medic", "ChestA")] = (-6f, -2f),
        [("medic", "ChestB")] = (-2f, -2f),
        [("medic", "Gun")] = (-4f, 0f),
        [("medic", "Head")] = (0f, -16f),
        [("medic", "LegBottomL")] = (-8f, 16f),
        [("medic", "LegBottomR")] = (0f, 16f),
        [("medic", "LegTopL")] = (-8f, 10f),
        [("medic", "LegTopR")] = (-2f, 12f),
        [("sniper", "ChestA")] = (-6f, -4f),
        [("sniper", "ChestB")] = (0f, 0f),
        [("sniper", "Gun")] = (4f, -2f),
        [("sniper", "Hat")] = (-4f, -22f),
        [("sniper", "Head")] = (-4f, -16f),
        [("sniper", "LegBottomL")] = (-10f, 18f),
        [("sniper", "LegBottomR")] = (2f, 18f),
        [("sniper", "LegTopL")] = (-8f, 8f),
        [("sniper", "LegTopR")] = (0f, 6f),
        [("spy", "ChestA")] = (-2f, -4f),
        [("spy", "ChestB")] = (0f, -4f),
        [("spy", "Gun")] = (12f, -4f),
        [("spy", "Head")] = (0f, -20f),
        [("spy", "LegBottom")] = (0f, 16f),
        [("spy", "LegTop")] = (-2f, 8f),
    };

    public static (float X, float Y) Get(string classId, string partName)
        => Offsets[(classId, partName)];
}
